/**
 * Itinerary Export Utilities
 * Functions to export itinerary as PDF, print, or text
 */

/**
 * Export itinerary as printable HTML
 */
export const exportItineraryAsHTML = (itinerary, tripDetails) => {
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>My Trip Itinerary - ${tripDetails.destination || 'Trip'}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      color: #333;
    }
    .header {
      text-align: center;
      border-bottom: 3px solid #4F46E5;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .trip-info {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 15px;
      margin-bottom: 30px;
      padding: 20px;
      background: #F3F4F6;
      border-radius: 8px;
    }
    .day-section {
      margin-bottom: 40px;
      page-break-inside: avoid;
    }
    .day-header {
      background: #4F46E5;
      color: white;
      padding: 15px;
      border-radius: 8px 8px 0 0;
      font-size: 1.2em;
      font-weight: bold;
    }
    .activity {
      padding: 15px;
      border: 1px solid #E5E7EB;
      border-top: none;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .activity:last-child {
      border-radius: 0 0 8px 8px;
    }
    .time {
      color: #6B7280;
      font-size: 0.9em;
    }
    @media print {
      body { margin: 0; padding: 10px; }
      .day-section { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>My Trip Itinerary</h1>
    <h2>${tripDetails.destination || 'Trip'}</h2>
    <p>${tripDetails.startDate ? new Date(tripDetails.startDate).toLocaleDateString() : ''} - ${tripDetails.endDate ? new Date(tripDetails.endDate).toLocaleDateString() : ''}</p>
  </div>
  
  <div class="trip-info">
    <div><strong>Destination:</strong> ${tripDetails.destination || 'N/A'}</div>
    <div><strong>Duration:</strong> ${itinerary.length} day${itinerary.length !== 1 ? 's' : ''}</div>
    <div><strong>Travel Type:</strong> ${tripDetails.travelType || 'N/A'}</div>
    <div><strong>Group Size:</strong> ${tripDetails.groupSize || 1} traveler${(tripDetails.groupSize || 1) !== 1 ? 's' : ''}</div>
  </div>
  
  ${itinerary.map((day, index) => `
    <div class="day-section">
      <div class="day-header">
        Day ${index + 1} - ${new Date(day.date).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
      </div>
      ${(day.activities || []).map(activity => `
        <div class="activity">
          <div>
            <strong>${activity.name || 'Activity'}</strong>
            ${activity.description ? `<div style="color: #6B7280; font-size: 0.9em; margin-top: 5px;">${activity.description}</div>` : ''}
          </div>
          <div class="time">
            ${activity.startTime || ''} - ${activity.endTime || ''}
          </div>
        </div>
      `).join('')}
      ${day.meals && (day.meals.breakfast || day.meals.lunch || day.meals.dinner) ? `
        <div style="padding: 15px; background: #FEF3C7; border: 1px solid #E5E7EB; border-top: none;">
          <strong>Meals:</strong>
          ${day.meals.breakfast ? `Breakfast: ${day.meals.breakfast.name || 'TBD'}` : ''}
          ${day.meals.lunch ? ` • Lunch: ${day.meals.lunch.name || 'TBD'}` : ''}
          ${day.meals.dinner ? ` • Dinner: ${day.meals.dinner.name || 'TBD'}` : ''}
        </div>
      ` : ''}
    </div>
  `).join('')}
  
  <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #E5E7EB; text-align: center; color: #6B7280; font-size: 0.9em;">
    Generated by BharatYatra AI – Smarter Journeys Across India
  </div>
</body>
</html>
  `;
  
  return html;
};

/**
 * Export itinerary as PDF (opens print dialog)
 */
export const exportItineraryAsPDF = (itinerary, tripDetails) => {
  const html = exportItineraryAsHTML(itinerary, tripDetails);
  const printWindow = window.open('', '_blank');
  printWindow.document.write(html);
  printWindow.document.close();
  
  // Wait for content to load, then print
  printWindow.onload = () => {
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };
};

/**
 * Export itinerary as plain text
 */
export const exportItineraryAsText = (itinerary, tripDetails) => {
  let text = `MY TRIP ITINERARY\n`;
  text += `==================\n\n`;
  text += `Destination: ${tripDetails.destination || 'N/A'}\n`;
  text += `Dates: ${tripDetails.startDate ? new Date(tripDetails.startDate).toLocaleDateString() : ''} - ${tripDetails.endDate ? new Date(tripDetails.endDate).toLocaleDateString() : ''}\n`;
  text += `Duration: ${itinerary.length} day${itinerary.length !== 1 ? 's' : ''}\n`;
  text += `Travel Type: ${tripDetails.travelType || 'N/A'}\n`;
  text += `Group Size: ${tripDetails.groupSize || 1} traveler${(tripDetails.groupSize || 1) !== 1 ? 's' : ''}\n\n`;
  text += `${'='.repeat(50)}\n\n`;
  
  itinerary.forEach((day, index) => {
    text += `DAY ${index + 1} - ${new Date(day.date).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}\n`;
    text += `${'-'.repeat(50)}\n\n`;
    
    (day.activities || []).forEach((activity, actIndex) => {
      text += `${actIndex + 1}. ${activity.name || 'Activity'}\n`;
      if (activity.startTime && activity.endTime) {
        text += `   Time: ${activity.startTime} - ${activity.endTime}\n`;
      }
      if (activity.description) {
        text += `   ${activity.description}\n`;
      }
      text += `\n`;
    });
    
    if (day.meals && (day.meals.breakfast || day.meals.lunch || day.meals.dinner)) {
      text += `Meals:\n`;
      if (day.meals.breakfast) text += `  Breakfast: ${day.meals.breakfast.name || 'TBD'}\n`;
      if (day.meals.lunch) text += `  Lunch: ${day.meals.lunch.name || 'TBD'}\n`;
      if (day.meals.dinner) text += `  Dinner: ${day.meals.dinner.name || 'TBD'}\n`;
      text += `\n`;
    }
    
    text += `\n`;
  });
  
  text += `\nGenerated by BharatYatra AI – Smarter Journeys Across India\n`;
  
  return text;
};

/**
 * Download itinerary as text file
 */
export const downloadItineraryAsText = (itinerary, tripDetails) => {
  const text = exportItineraryAsText(itinerary, tripDetails);
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `itinerary-${tripDetails.destination || 'trip'}-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Share itinerary via email
 */
export const shareItineraryViaEmail = (itinerary, tripDetails) => {
  const text = exportItineraryAsText(itinerary, tripDetails);
  const subject = encodeURIComponent(`My Trip Itinerary - ${tripDetails.destination || 'Trip'}`);
  const body = encodeURIComponent(text);
  const mailtoLink = `mailto:?subject=${subject}&body=${body}`;
  window.location.href = mailtoLink;
};

/**
 * Share itinerary via social media
 */
export const shareItineraryViaSocial = (itinerary, tripDetails, platform) => {
  const text = `Check out my trip itinerary for ${tripDetails.destination || 'my trip'}! ${tripDetails.startDate ? `Dates: ${new Date(tripDetails.startDate).toLocaleDateString()} - ${new Date(tripDetails.endDate).toLocaleDateString()}` : ''}`;
  const url = encodeURIComponent(window.location.href);
  const encodedText = encodeURIComponent(text);

  const shareUrls = {
    twitter: `https://twitter.com/intent/tweet?text=${encodedText}&url=${url}`,
    facebook: `https://www.facebook.com/sharer/sharer.php?u=${url}&quote=${encodedText}`,
    whatsapp: `https://wa.me/?text=${encodedText}%20${url}`,
    linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${url}`
  };

  if (shareUrls[platform]) {
    window.open(shareUrls[platform], '_blank', 'width=600,height=400');
  }
};

/**
 * Copy itinerary link to clipboard
 */
export const copyItineraryLink = async () => {
  try {
    await navigator.clipboard.writeText(window.location.href);
    return true;
  } catch (err) {
    console.error('Failed to copy link:', err);
    // Fallback for older browsers
    const textArea = document.createElement('textarea');
    textArea.value = window.location.href;
    document.body.appendChild(textArea);
    textArea.select();
    try {
      document.execCommand('copy');
      document.body.removeChild(textArea);
      return true;
    } catch (fallbackErr) {
      document.body.removeChild(textArea);
      return false;
    }
  }
};

